vaadin:
  launch-browser: true
gg:
  jte:
    development-mode: true
spring:
  application:
    name: library-admin-client

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${AUTH_HOSTNAME}:${AUTH_PORT}/oauth2/jwks
      client:
        registration:
          library-admin-client:
            provider: libraryprov
            client-id: library-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://${ADMIN_HOSTNAME}:${ADMIN_PORT}/login/oauth2/code/{registrationId}
            scope: adminStuff,openid
        provider:
          libraryprov:
            issuer-uri: http://${AUTH_HOSTNAME}:${AUTH_PORT}

server:
  port: ${ADMIN_PORT}